RECIPE_URLS = "./recommendation_system/dataset/Full_recipesDetails.csv"
RECIPES_DETAILS = "./recommendation_system/dataset/Full_recipesDetails.csv"
MODEL = "./recommendation_system/model_cbow.bin"
customhost = "ingrechef.c9ykhllwofkw.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "IngreChef"
customregion = "us-east-1"